### ISSUE TITLE
Empty post content generates a Warning

### ISSUE THREAD

**Issue by lpointet** [uncatcrea/q-android#11]
If one of the posts returned by WP-AppKit webservice is empty (an empty content), synchronization webservice returns with the following warning:
`Warning: DOMDocument::loadHTML(): Empty string supplied as input in wp-content/themes-wp-appkit/q-android/php/prepare-content.php on line 13`

Locally, I used the following fix:
```
function wpak_prepare_content($content,$post){
	// Bail in case of empty content
	if( empty( $content ) ) {
		return $content;
	}

	// Rest of the function...
}
```

**Comment by mleroi** [comment]
This is fixed and should be embedded in next WP-AppKit version, as said here: https://github.com/uncatcrea/wp-appkit/issues/321
