### ISSUE TITLE
Branch for user login/registration on Q for Android and iOS

### ISSUE THREAD

**Issue by HammyHavoc** [uncatcrea/q-android#20]
This was a really useful example on the original theme; is there a branch for this on Q?

**Comment by blupu** [comment]
Hi, unfortunatly no. This is something we could do. At the moment, we're preparing a coming event (WPTech). So we can't jump into this right now.

**Comment by mleroi** [comment]
There is now one here: https://github.com/mleroi/q-android/tree/feat-authentication :)
