### ISSUE TITLE
Q for Android content update

### ISSUE THREAD

**Issue by hakansenturk** [uncatcrea/q-android#4]
, as you suggested I replaced the line **App.navigateToDefaultRoute();** in functions.js with the following;

// Navigate to the default screen
        
        
         var currentScreenObject = App.getCurrentScreenObject();

    // Navigate to the default screen (if we are not displaying a single) 
    if ( currentScreenObject.screen_type !== 'single' ) {
        App.navigateToDefaultRoute();
    }

it works :-), but the problem is after refresh is completed, I cannot go back to previous screen by pressing the back arrow button on the screen. But I can only go back by pressing the phone's back button. I could not find the solution for this.

**Comment by blupu** [comment]
Hi @hakansenturk well we've done some research and you clearly spotted a bug in WP-AppKit core. We have open an issue about it: https://github.com/uncatcrea/wp-appkit/issues/262.

In the meantime, you can use the _make-history_ filter in _functions.js_ to solve your problem.

```javascript
App.filter('make-history',function( history_action, history_stack, queried_screen, current_screen, previous_screen ){
	if( queried_screen.screen_type === 'single' && current_screen.screen_type === 'single' 
		&& queried_screen.item_id === current_screen.item_id ) { 
		//If we redisplay the same single (which happens after a refresh if we don't go back to default route), 
		//don't modify history:
		history_action = 'none';
	}
	return history_action;
});
```
