### ISSUE TITLE
Videos imbedded in iframes do not display

### ISSUE THREAD

**Issue by blupu** [uncatcrea/q-android#5]
_Transferring issue #14 from https://github.com/uncatcrea/wpak-off-canvas-themes - https://github.com/uncatcrea/wpak-off-canvas-themes/issues/14#issuecomment-258311920_

Original post from https://github.com/levybee:

> Hi,
> Thank you for the great work. I have an issue regarding embedded videos using iframes, they do not > show on the app.

> I tried editing prepare-content.php and removed this part:

> foreach($iframeCollection as $iframe) { $iframe->setAttribute('data-src',$iframe->getAttribute('src')); > $iframe->setAttribute('src',''); }

> and functions.js

> // Remove all iframes to get a smooth closing transition (notably because of YouTube iframes) //$('#' + currentContainerId + ' ' + 'iframe').remove();

> and

> // We defer video loading to keep transitions smooth //loadAndFormatVideosFor( currentScreenObject );

> but I still have the same problem. However when I embed the iframe code directly into single.html template the video gets displayed. Could there be a script that strips the iframe tags?

> Thank you,

> Levy

**Comment by blupu** [comment]
Hi @levybee, I reproduce your problem on an app compiled with cli-6.3.0 as PhoneGap Version and running on iOS9 or iOS10. I believe it is related to the new iOS webview support. This new webview might have stronger security regarding iframes. I am going to dig that. In the meantime, you can resolve your issue downgrading to cli-5.4.1 for PhoneGap Version (in app's Edit > PhoneGap > Version). It solves the video display problem.

**Comment by levybee** [comment]
Hi @blupu, I tried downgrading PhoneGap Version to cli-5.4.1 but I still have the same problem. I am running the app on Android Version 4.4.2. I have seen something about a whitelist plugin https://www.npmjs.com/package/cordova-plugin-whitelist . Tried adding that but it doesn't fix it.

**Comment by blupu** [comment]
OK. I clearly reproduce your problem on iOS **only** and only using cli-6x. I've tested both cli-5x and cli-6x on Android and video embeds **works**.

Regarding _cordova-plugin-whitelist_, it is included and configured by default by WP-AppKit (you can see it in _config.xml_).

3 questions:
- Are you sure you chose _Android_ as platform for your app?
- Are you sure you use _Q for Android_ theme? 
- Is the video lazy loading code still removed in your theme?

**Comment by levybee** [comment]
@blupu , I got it to work. I had modified Q for Android and somehow I must have tweaked with the functions.js file and messed something up. I replace the file with the original one from Q for Android and the iframe showed. 

Thank you for your help.

**Comment by blupu** [comment]
Glad to hear that you've solved your issue (building applications can be tricky sometimes). Don't hesitate to tell what you build :)
